language: ruby
rvm:
  - 2.4.0
env:
  - CODECLIMATE_REPO_TOKEN: 4a3d18e723d4ee08cad15db645261022bd271353451857767580d6fe0ac13d0a
after_success:
  - bundle exec codeclimate-test-reporter
notifications:
  slack: navyblue-team:ioO5diAGc5WUQVDKc5BH1UbE
  email: false